#import "./projectFragment.gql"

query projects($skip: Int, $limit: Int) {
  projects(skip: $skip, limit: $limit) {
    total
    data{
      ...project
    },
    allData{
      ...project
    }
  }
}
